export const STATFETCHSTART = "STATFETCHSTART";
export const STATFETCHSUCCESS = "STATFETCHSUCCESS";
export const STATFETCHFAIL = "STATFETCHFAIL";

export const HOMECOINSTART = "HOMECOINSTART";
export const HOMECOINSUCCESS = "HOMECOINSUCCESS";
export const HOMECOINFAIL = "HOMECOINFAIL";

export const FETCHCOINSTART = "FETCHCOINSTART";
export const FETCHCOINSUCCESS = "FETCHCOINSUCCESS";
export const FETCHCOINFAIL = "FETCHCOINFAIL";

export const HOMENEWSSTART = "HOMENEWSSTART";
export const HOMENEWSSUCCESS = "HOMENEWSSUCCESS";
export const HOMENEWSFAIL = "HOMENEWSFAIL";

export const FETCHNEWSSTART = "FETCHNEWSSTART";
export const FETCHNEWSSUCCESS = "FETCHNEWSSUCCESS";
export const FETCHNEWSFAIL = "FETCHNEWSFAIL";

export const HISTORYFETCHSTATRT = "HISTORYFETCHSTATRT";
export const HISTORYFETCHSUCCESS = "HISTORYFETCHSUCCESS";
export const HISTORYFETCHFAIL = "HISTORYFETCHFAIL";

export const CREATENOTE = "CREATENOTE";
export const DELETENOTE = "DELETENOTE";
